#!/bin/sh

# An example hook script to verify what is about to be pushed.  Called by "git
# push" after it has checked the remote status, but before anything has been
# pushed.  If this script exits with a non-zero status nothing will be pushed.
#
# This will run your unit test and sets the exit code base on failure or success
# 
# It will hide your unit test report and a regex is required to display the 
# line from the report, that would summarize your unit test result.
#
# This hook is called with the following parameters:
# 1. the unit test executable
# 2. line regex of the test summary

TEST_CMD="npx ng test --single-run --progress=false --sm=false --log-level=error"

run_test() {
    report=$($1)
    result=$?
    echo "$report"
    exit $result
}

echo -e "\033[0;33m\tRunning test before pushing...\033[0m"

run_test "${TEST_CMD}"
