#!/bin/sh
#
# Hook to stop commits if any debug code is left behind
#
# As well it prevents focus specs to be added
#
# This hook has two functions:
# 1. check for lint issues (You'll have to fix it on your own)
# 2. check for debug lines
# 3. check for focused specs (looks for .spec.js. Rename line 37 if your test files have a different convention)
#
# Both function expects two parameters:
# 1. the file type
# 2. the regex to look for
#
# FIXME: the check_debug for some reason can't diff on the parameter ¯\_(ツ)_/¯

EXIT_VALUE=0

LINT_CMD="npx ng lint --format stylish"
run_lint() {
    report=$($1)
    result=$?
    echo "$report"
    exit $result
}

check_debug() {
    debug_result="$(git diff --cached "**.js" "**.ts" | egrep "^\+" | grep -E $1)"
    echo "$debug_result"
    if [ ! -z "$debug_result" ]; then
        echo -e "\033[0;31m\tWarning, the commit contains debug code. Please remove before commiting.\033[0m"
        EXIT_VALUE=1
    fi
}

check_fspec() {
    fspec_result="$(git diff --cached $1 | egrep "^\+" | grep -E $2)"
    if [ ! -z "$fspec_result" ]; then
        echo -e "\033[0;31m\tWarning, the commit contains focused specs. Please fix this before commiting.\033[0m"
        EXIT_VALUE=1
    fi    
}

check_debug "(debugger|console)"
check_fspec *.spec.ts "(fdescribe|fit|fcontext)"

if [ "$EXIT_VALUE" != 0 ]; then
    exit $EXIT_VALUE
fi

run_lint "${LINT_CMD}"

exit $EXIT_VALUE
